### ISSUE TITLE
Cross DC functional tests: could not load LogManager class before starting the tests

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#1011]
### Describe the bug

In our current Cross DC functional tests, we see a message like the below one in each of the functional test run.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:650)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:720)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:703)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.setupJunitLogger(JUnitPlatformProvider.java:133)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:116)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

### Version

keycloak-benchmark latest main

### Expected behavior

We should not see a failure message without understanding the impact of the failure message and remove the error message from our log stream if its not relevant.

**Comment by ahus1** [comment]
@kami619 - as this is a relatively small thing that needs to clean up I wouldn't plan it for a sprint and instead just clean it up. 

Would you know what to change to fix it, or would you like someone else to look at it?
