### ISSUE TITLE
dataset is using deprecated API, causing logs to fill with warnings

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-benchmark#193]
### Description

dataset module is calling `session.userCredentialManager()` when setting user credentials. There's a deprecation warning that fills up the logs.

### Motivation

Use current APIs.

### Details

```
2022-09-08 21:03:46,154 WARN  [org.keycloak.credential.UserCredentialStoreManager] (pool-13-thread-5) Calls to session.userCredentialManager() now deprecated. Use user.userCredentialManager() instead!: java.lang.RuntimeException
	at org.keycloak.credential.UserCredentialStoreManager.warnAboutUsage(UserCredentialStoreManager.java:206)
	at org.keycloak.credential.UserCredentialStoreManager.updateCredential(UserCredentialStoreManager.java:144)
	at org.keycloak.benchmark.dataset.DatasetResourceProvider.createUsers(DatasetResourceProvider.java:949)
	at org.keycloak.benchmark.dataset.DatasetResourceProvider.lambda$addUserCreationTasks$11(DatasetResourceProvider.java:412)
```

**Comment by ahus1** [comment]
Thanks for reporting this, this will be handled in #179. Closing this as a duplicate.

**Comment by ahus1** [comment]
(This warning indicates that some actions of the dataset provider fail ... please suspend tests using the dataset provider on KC19 or later until the other issue is fixed)
