### ISSUE TITLE
Running Different scenarios mentioned in docs result in error

### ISSUE THREAD

**Issue by nehachopra27** [keycloak/keycloak-benchmark#249]
### Describe the bug

When running the  script ./kcb.sh with different scenarios here https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario-overview

`./kcb.sh --scenario=keycloak.scenario.admin.CreateRealm --admin-username=admin --admin-password=admin --server-url=http://keycloak.*.*.*.*.nip.io/ --realm-name=test-realm`

### Version

0.9 SNAPSHOT

### Expected behavior

Tests should run successfully

### Actual behavior

17:05:05.797 [INFO ] a.e.s.Slf4jLogger - Slf4jLogger started
17:05:05.920 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: keycloak.scenario.admin.CreateRealm
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:71)
	at scala.util.Try$.apply(Try.scala:213)
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:71)
	... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class keycloak.scenario.admin.CreateRealm could not be loaded
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:80)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:85)
	at scala.Option.orElse(Option.scala:447)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:85)
	at scala.Option.flatMap(Option.scala:271)
	at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:83)
	at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
	at scala.Option.getOrElse(Option.scala:189)
	at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
	at io.gatling.app.Selection$.apply(Selection.scala:36)
	at io.gatling.app.Runner.run0(Runner.scala:64)
	at io.gatling.app.Runner.run(Runner.scala:52)
	at io.gatling.app.Gatling$.start(Gatling.scala:80)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class keycloak.scenario.admin.CreateRealm could not be loaded
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:80)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:85)
	at scala.Option.orElse(Option.scala:447)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:85)
	at scala.Option.flatMap(Option.scala:271)
	at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:83)
	at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
	at scala.Option.getOrElse(Option.scala:189)
	at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
	at io.gatling.app.Selection$.apply(Selection.scala:36)
	at io.gatling.app.Runner.run0(Runner.scala:64)
	at io.gatling.app.Runner.run(Runner.scala:52)
	at io.gatling.app.Gatling$.start(Gatling.scala:80)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
	at io.gatling.app.Gatling$.main(Gatling.scala:37)
	at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: keycloak.scenario.admin.CreateRealm
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:71)
	at scala.util.Try$.apply(Try.scala:213)
	at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:71)
	... 15 more

### How to Reproduce?

./kcb.sh --scenario=keycloak.scenario.admin.CreateRealm --admin-username=admin --admin-password=admin --server-url=http://keycloak.*.*.*.*.nip.io/ --realm-name=test-realm

### Anything else?

Running tests on MacOS
The steps are missing in the scenarios here https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario/create-realm

It would have been useful to debug.

**Comment by ahus1** [comment]
Hi @nehachopra27 - thanks for reporting this. It seems that the docs are wrong about the class name, the docs miss the "s" at the end. 

Could you please try `keycloak.scenario.admin.CreateRealms` instead, and if this works, update the docs?

It seems to me that also https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario-overview needs to be updated. 

Thanks!

**Comment by nehachopra27** [comment]
Hi @ahus1,

Thanks, the solution worked for me. sent a PR for all the scenarios that needed the corresponding update in the names.
