### ISSUE TITLE
RH-SSO 7.6.2 + keycloak-benchmark-dataset-0.7.jar : Fails to create entities

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#303]
### Describe the bug

RH-SSO 7.6.2 + keycloak-benchmark-dataset-0.7.jar : Fails to create entities

when I deploy that to a hosted RH-SSO on OCP, it fails to create the new entities with the below exception when I run the below command,

curl https://keycloak-rh-sso.apps.kamesh.keycloak-team.engineering.redhat.com/auth/realms/master/dataset/create-realms?count=10

```
[0m [0m11:36:22,301 INFO  [org.jboss.as.repository] (DeploymentScanner-threads - 1) WFLYDR0001: Content added at location /opt/eap/standalone/data/content/16/aa58b52b0772e7fffc1c0479b827b183febeaa/content
[0m [0m11:36:22,303 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "keycloak-benchmark-dataset-0.7.jar" (runtime-name: "keycloak-benchmark-dataset-0.7.jar")
[0m [33m11:36:22,340 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-benchmark-dataset-0.7.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.
[0m [33m11:36:22,341 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-benchmark-dataset-0.7.jar" is using a private module ("org.keycloak.keycloak-model-infinispan") which may be changed or removed in future versions without notice.
[0m [33m11:36:22,341 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-benchmark-dataset-0.7.jar" is using a private module ("org.infinispan.persistence.remote") which may be changed or removed in future versions without notice.
[0m [0m11:36:22,342 INFO  [org.keycloak.subsystem.server.extension.KeycloakProviderDeploymentProcessor] (MSC service thread 1-1) Deploying Keycloak provider: keycloak-benchmark-dataset-0.7.jar
[0m [0m11:36:22,390 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0010: Deployed "keycloak-benchmark-dataset-0.7.jar" (runtime-name : "keycloak-benchmark-dataset-0.7.jar")
[0m [31m11:37:12,813 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-11) Uncaught server error: java.lang.NoSuchMethodError: 'javax.ws.rs.core.UriInfo org.jboss.resteasy.spi.HttpRequest.getUri()'
at deployment.keycloak-benchmark-dataset-0.7.jar//org.keycloak.benchmark.dataset.config.ConfigUtil.createConfigFromQueryParams(ConfigUtil.java:54)
at deployment.keycloak-benchmark-dataset-0.7.jar//org.keycloak.benchmark.dataset.DatasetResourceProvider.createClients(DatasetResourceProvider.java:243)
```

**Full log attached for your reference**

I think we need a path to overcome and backport these fixes to keycloak-benchmark-dataset-0.7 as a hotfix, to be able to create larger datasets on RH-SSO 7.6.2. I can schedule something tomorrow, if you think that's warrants a discussion.

[keycloak-0-keycloak.log](https://github.com/keycloak/keycloak-benchmark/files/11112770/keycloak-0-keycloak.log)

### Version

RH-SSO 7.6.2

### Expected behavior

curl https://keycloak-rh-sso******/auth/realms/master/dataset/create-realms?count=10

This api request should be able to create 10 realms agains the hosted keycloak application

### Actual behavior

it fails with an exception

**Comment by kami619** [comment]
that was a super fast response @ahus1 I will try that out and see how it goes. thanks so much.

**Comment by kami619** [comment]
and it works as expected @ahus1 this unblocks our work, appreciate it.

**Comment by ahus1** [comment]
Happy to help!
