### ISSUE TITLE
Local gossip router killed infinispan stalling problem

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak-benchmark#675]
The scenario involves testing the behavior when a Gossip Router (GR) pod crashes during the load. The crash is simulated by killing the GR and disabling the health checks to prevent OCP from starting a new pod again.

The commands used are:
```
oc delete pods -l app=infinispan-router-pod --force --grace-period=0
oc delete deployment/infinispan-router
```

In summary, the stalling happens because the traffic goes through a `ClusterIP` type of `Service`. It has a proxy to handle the traffic and it keeps the TCP connection open even after the GR pod is killed. The Infinispan pod threads start blocking in the `Socket.write()` which leads to timeouts and other errors. The Infinispan cluster recovers after some entity (container OS, host OS, openshift?) kills and closes the TCP connection.

**Comment by pruivo** [comment]
More details follow.

Run the scenario described and collect the following information. For the record, the GR pod was killed around 11:19.

```
[trigger-failover] INFO:2024-01-10-11:19:40-WET Running Failover scenario - GOSSIP_ROUTER_FAIL
```

In a single Infinispan pod, the network stats were inspected via `ss` (replaces `neststat` Linux command) at some random times. 
```
[1001070000@infinispan-0 infinispan]$ date && ss -na | grep 7900
Wed Jan 10 11:29:15 UTC 2024
tcp   ESTAB      0      367300   10.128.4.21:44625    172.30.44.106:7900        

[1001070000@infinispan-0 infinispan]$ date && ss -na | grep 7900
Wed Jan 10 11:35:16 UTC 2024
tcp   FIN-WAIT-1 0      367301   10.128.4.21:44625    172.30.44.106:7900        

[1001070000@infinispan-0 infinispan]$ date && ss -na | grep 7900
Wed Jan 10 11:44:25 UTC 2024
```

We can observe that there is ~367kb of data pending in the TCP sending queue and the TCP connection is established even after 10 min after the `delete` command. 15 minutes later, it reaches the `FIN-WAIT-1` (ISPN pod sends `FIN` request send and waits for `FIN-ACK` - it will timeout).

**Comment by ahus1** [comment]
Good to know it eventually recovers. At the same time something similar could happen if there is an very slow connection (think: 1 byte per second) connection. 

I would expect that the remote site would eventually be marked offline after some timeouts, retries and closed connections.

**Comment by pruivo** [comment]
Adding thread information missing. Threads are blocked in the `write()` method since the TCP send queue is full. 

```
"TQ-Bundler-5,xsite,_infinispan-0-20952:pruivo-b@12130" prio=5 tid=0x28 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks jgroups-22,xsite,_infinispan-0-20952:pruivo-b@12175
	  at sun.nio.ch.FileDispatcherImpl.write0(FileDispatcherImpl.java:-1)
	  at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
	  at sun.nio.ch.NioSocketImpl.tryWrite(NioSocketImpl.java:403)
	  at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:418)
	  at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
	  at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831)
	  at java.net.Socket$SocketOutputStream.write(Socket.java:1035)
```

GR heartbeats thread is blocked as well. Unable to send the heartbeat and unable to check for timeouts:

```
"jgroups-22,xsite,_infinispan-0-20952:pruivo-b@12175" prio=5 tid=0x98 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks jgroups-21,xsite,_infinispan-0-20952:pruivo-b@12174
	 waiting for TQ-Bundler-5,xsite,_infinispan-0-20952:pruivo-b@12130 to release lock on <0x307f> (a org.jgroups.stack.RouterStub)
	  at org.jgroups.stack.RouterStub.writeRequest(RouterStub.java:263)
	  at org.jgroups.stack.RouterStubManager.lambda$sendHeartbeat$5(RouterStubManager.java:272)
```
```
"jgroups-21,xsite,_infinispan-0-20952:pruivo-b@12174" prio=5 tid=0x96 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for jgroups-22,xsite,_infinispan-0-20952:pruivo-b@12175 to release lock on <0x3082> (a java.util.ArrayList)
	  at org.jgroups.stack.RouterStubManager.forEach(RouterStubManager.java:100)
	  at org.jgroups.stack.RouterStubManager.checkTimeouts(RouterStubManager.java:281)
```

And patched JGroups version was tested to avoid those synchronized blocks and a thread make progress trying to close the socket. However, the `close()` tries to flush and terminate the TLS session and did not solve the problem:

```
"jgroups-9,xsite,_infinispan-2-2367:pruivo-b@12112" prio=5 tid=0x5d nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
	  at java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
	  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
	  at sun.security.ssl.SSLSocketImpl.closeNotify(SSLSocketImpl.java:735)
	  at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:661)
	  at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:584)
	  at org.jgroups.util.Util.close(Util.java:469)
	  at org.jgroups.blocks.cs.TcpConnection.close(TcpConnection.java:394)
	  at org.jgroups.util.Util.close(Util.java:469)
	  at org.jgroups.blocks.cs.TcpClient.stop(TcpClient.java:78)
	  at org.jgroups.blocks.cs.BaseServer.close(BaseServer.java:170)
	  at org.jgroups.util.Util.close(Util.java:469)
	  at org.jgroups.stack.RouterStub.destroy(RouterStub.java:139)
	  at org.jgroups.stack.RouterStubManager.lambda$checkTimeouts$6(RouterStubManager.java:269)
```

**Comment by pruivo** [comment]
> Good to know it eventually recovers. At the same time something similar could happen if there is an very slow connection (think: 1 byte per second) connection.
> 
> I would expect that the remote site would eventually be marked offline after some timeouts, retries and closed connections.

I think it would have the same problem with the same outcome. `write()` would block due to the slow connection and progress won't be made.

Maybe JGroups can detect how long a thread takes inside `TcpConnection.send` and interrupt if some threshold is hit. But I'm not convinced that it fixes the issue. 

cc @belaban

**Comment by belaban** [comment]
So close() blocks because it flushes the output stream (TCP write), but some other thread already is already writing and has the lock. Hmm, I don't think we can fix this, but at least we could mark the connection as `disconnected` _before_ closing it, so subsequent messages don't use this route. The question is will the bundler bloock until this connection unblocks? Investigating...

**Comment by pruivo** [comment]
SSL socket blocking is know issue: https://bugs.openjdk.org/browse/JDK-8241239

**Comment by pruivo** [comment]
[Kraken Chaos tool](https://github.com/redhat-chaos/krknChaos-hub/blob/main/docs/pod-scenarios.md) seems to achieve the same outcome.

**Comment by pruivo** [comment]
Just to keep everything linked, 2 more issues possibly related to this:
https://issues.redhat.com/browse/JGRP-2752
https://issues.redhat.com/browse/JGRP-2753
