### ISSUE TITLE
RH-SSO 7.6.6.GA + keycloak-benchmark-dataset-0.7.rhsso-SNAPSHOT.jar : Uncaught server error: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by damonhuangoocl** [keycloak/keycloak-benchmark#808]
### Describe the bug

RH-SSO 7.6.6.GA + keycloak-benchmark-dataset-0.7.rhsso-SNAPSHOT.jar : Uncaught server error: java.lang.NoClassDefFoundError

When I deploy keycloak-benchmark to RH-SSO, it fail to call the status API with the below exception when I run the below command

`GET https://sso.common-xxxxxx.network/auth/realms/master/dataset/status`

```
2024-05-13T01:47:32.644531195Z 01:47:32,644 DEBUG [org.keycloak.provider.FileSystemProviderLoaderFactory] (ServerService Thread Pool -- 69) Loading providers from [file:/opt/jboss/keycloak/providers/gsbn-keycloak-email-template.jar, file:/opt/jboss/keycloak/providers/keycloak-benchmark-dataset-0.7.rhsso-SNAPSHOT.jar]
01:57:41,482 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.NoClassDefFoundError: org/infinispan/commons/api/BasicCache 2024-05-13T01:57:41.483795009Z at org.keycloak.benchmark.dataset.DatasetResourceProvider.getStatus(DatasetResourceProvider.java:730) 2024-05-13T01:57:41.483807809Z at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 2024-05-13T01:57:41.483816609Z at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 2024-05-13T01:57:41.483825210Z at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
Mon, May 13 2024 9:57:41 am at java.base/java.lang.reflect.Method.invoke(Method.java:566) 2024-05-13T01:57:41.483843310Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138) 2024-05-13T01:57:41.483852610Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546) 2024-05-13T01:57:41.483860210Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435) 2024-05-13T01:57:41.483867910Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396) 
Mon, May 13 2024 9:57:41 am at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) 2024-05-13T01:57:41.483883610Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398) 2024-05-13T01:57:41.483901410Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365) 
Mon, May 13 2024 9:57:41 am at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150) 2024-05-13T01:57:41.483932110Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104) 2024-05-13T01:57:41.483939910Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440) 2024-05-13T01:57:41.483947410Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229) 
Mon, May 13 2024 9:57:41 am at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135) 
Mon, May 13 2024 9:57:41 am at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358) 2024-05-13T01:57:41.483970710Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138) 2024-05-13T01:57:41.483991711Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215) 2024-05-13T01:57:41.484002211Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245) 2024-05-13T01:57:41.484009311Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61) 2024-05-13T01:57:41.484020111Z at org.jboss.resteasy.resteasy-jaxrs@3.15.8.Final-redhat-00001//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) 2024-05-13T01:57:41.484025011Z at javax.servlet.api@2.0.0.Final-redhat-00001//javax.servlet.http.HttpServlet.service(HttpServlet.java:590) 2024-05-13T01:57:41.484029011Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) 2024-05-13T01:57:41.484033011Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) 
Mon, May 13 2024 9:57:41 am at org.keycloak.keycloak-wildfly-extensions@18.0.11.redhat-00001//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41) 2024-05-13T01:57:41.484084011Z at org.keycloak.keycloak-services@18.0.11.redhat-00001//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43) 2024-05-13T01:57:41.484093411Z at org.keycloak.keycloak-wildfly-extensions@18.0.11.redhat-00001//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39) 2024-05-13T01:57:41.484101711Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) 2024-05-13T01:57:41.484110111Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) 
Mon, May 13 2024 9:57:41 am at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) 2024-05-13T01:57:41.484128712Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) 2024-05-13T01:57:41.484147612Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) 2024-05-13T01:57:41.484156112Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) 2024-05-13T01:57:41.484163812Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) 2024-05-13T01:57:41.484171412Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 2024-05-13T01:57:41.484182912Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) 2024-05-13T01:57:41.484190312Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) 2024-05-13T01:57:41.484197212Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) 2024-05-13T01:57:41.484204212Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 2024-05-13T01:57:41.484211412Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) 2024-05-13T01:57:41.4842211
Sat, Dec 1 2001 8:00:00 am at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) 
Mon, May 13 2024 9:57:41 am at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) 2024-05-13T01:57:41.484236712Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) 2024-05-13T01:57:41.484243812Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) 2024-05-13T01:57:41.484251112Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) 
Mon, May 13 2024 9:57:41 am at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 2024-05-13T01:57:41.484266312Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) 2024-05-13T01:57:41.484271212Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 2024-05-13T01:57:41.484279013Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) 2024-05-13T01:57:41.484286513Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) 2024-05-13T01:57:41.484315713Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 2024-05-13T01:57:41.484330613Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) 2024-05-13T01:57:41.484347713Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) 2024-05-13T01:57:41.484355513Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) 2024-05-13T01:57:41.484363113Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) 2024-05-13T01:57:41.484371013Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) 2024-05-13T01:57:41.484379213Z at io.undertow.servlet@2.2.26.SP2-redhat-0000
1//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) 
Mon, May 13 2024 9:57:41 am at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) 2024-05-13T01:57:41.484396413Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555) 2024-05-13T01:57:41.484404113Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555) 2024-05-13T01:57:41.484413713Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555) 2024-05-13T01:57:41.484421513Z at org.wildfly.extension.undertow@7.4.13.GA-redhat-00001//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1555) 2024-05-13T01:57:41.484428914Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) 
Mon, May 13 2024 9:57:41 am at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) 2024-05-13T01:57:41.484444314Z at io.undertow.servlet@2.2.26.SP2-redhat-00001//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) 2024-05-13T01:57:41.484451014Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) 2024-05-13T01:57:41.484455014Z at io.undertow.core@2.2.26.SP2-redhat-00001//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) 2024-05-13T01:57:41.484461714Z at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) 2024-05-13T01:57:41.484469214Z at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) 2024-05-13T01:57:41.484477314Z at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) 2024-05-13T01:57:41.484497114Z at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) 2024-05-13T01:57:41.484505714Z at org.jboss.xnio@3.8.10.Final-redhat-00001//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) 2024-05-13T01:57:41.484513314Z at java.base/java.lang.Thread.run(Thread.java:829) 2024-05-13T01:57:41.484520614Z Caused by: java.lang.ClassNotFoundException: org.infinispan.commons.api.BasicCache 2024-05-13T01:57:41.484535414Z at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476) 2024-05-13T01:57:41.484543514Z at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594) 2024-05-13T01:57:41.484551014Z at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527) 2024-05-13T01:57:41.484558514Z ... 75 more 2024-05-13T01:57:41.484565514Z 
```

### Version

RH-SSO 7.6.6.GA

### Expected behavior

{
    "status": "No task in progress. New task can be started"
}

### Actual behavior

fail to call

**Comment by ahus1** [comment]
Sorry for the late response. Closing this for inactivity on our side. Please comment if it is still relevant to you.
